name: Build and Push to Dockerfile Hub

on:
  push:
    branches:
      - master  # Runs when changes are pushed to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Dockerfile Hub
      - name: Log in to Dockerfile Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build Dockerfile Image with build number
      - name: Build Dockerfile Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }} .

      # Step 4: Push Dockerfile Image
      - name: Push Dockerfile Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/is147:${{ github.run_number }}